name: av_asian_life
description: Asian Life App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+362

#07/22/21
#ios = 2.0.0+361
#android = 2.0.0+361
#07/22/21
#ios = 2.0.0+360
#andorid = 2.0.0+360

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  trust_fall: ^1.0.4
  local_auth: ^0.6.0+1
  geolocator: ^5.1.3
  qr_flutter: ^3.0.1
  barcode_scan: ^1.0.0
  url_launcher: ^5.2.4
  query_params: ^0.6.1
  flutter_datetime_picker: ^1.5.0
  pin_code_text_field: ^1.2.1
  shared_preferences: ^0.5.3+4
  intro_slider: ^2.2.8
  image_picker: ^0.6.7+7
  flutter_launcher_icons: ^0.7.3
  app_settings: 4.0.1+1
  ssh: ^0.0.7
  percent_indicator: ^2.1.1+1
  file_picker: ^1.13.3
  package_info: ^0.4.0+3
  imei_plugin: ^1.1.4
  flutter_string_encryption: ^0.3.1
  autocomplete_textfield: ^1.6.4
  flutter_windowmanager: ^0.0.1+1
  firebase_messaging: ^7.0.0
  #firebase_analytics: ^6.0.0
  menu_button: ^1.2.1
  matrix_gesture_detector: ^0.1.0
  flutter_svg: ^0.18.0
  flutter_downloader: ^1.4.4
  permission_handler: ^4.4.0
  ext_storage: ^1.0.3
  dio:
  flutter_pdfview: ^1.0.1
  http: ^0.12.0+4
  path_provider: any
  upgrader: ^2.8.2
  share: ^2.0.1
  progress_dialog: ^1.2.4
  intl: ^0.16.1
  flutter_html: ^0.8.2
  pattern_formatter: ^1.0.2

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/ic_launcher_app.png'

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/email_v1.png
    - assets/images/EtiqaLogoBW_SmileApp.png
    - assets/images/EtiqaLogoColored_SmileApp.png
    - assets/images/facial_scan_v1.png
    - assets/images/FB_SMILE_APP.png
    - assets/images/FindDoctors_v1.png
    - assets/images/FindHospitals_v1.png
    - assets/images/fingerprint_v1.png
    - assets/images/GLRequest_v1.png
    - assets/images/IG_SMILE_APP.png
    - assets/images/Inquiries_v1.png
    - assets/images/LinkedIN_SMILE_APP.png
    - assets/images/Website_SMILE_APP.png
    - assets/images/qrcode_placeholder.png
    - assets/images/loading_Icon_v1.gif
    - assets/images/smile_app_icon_lg.png
    - assets/images/smile_app_icon_sm.png
    - assets/images/smile_app_icon_sm_2.png
    - assets/images/background.jpg
    - assets/images/background_opacity.png
    - assets/images/appBar_background.png
    - assets/images/intro_view_account.png
    - assets/images/req_log.png
    - assets/images/search.png
    - assets/images/default_profile_img.png
    - assets/images/smile_text.png
    - assets/images/face_id_finger_scan_v1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Abel
     fonts:
       - asset: assets/fonts/Abel-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
